version: "3.7"
services:

  jaeger:
    container_name: jaeger
    image: jaegertracing/all-in-one:1.22
    ports:
      - 5775:5775
      - 6831:6831
      - 6832:6832
      - 5778:5778
      - 16686:16686
      - 14268:14268
      - 14250:14250
      - 4317:4317

  zipkin:
    container_name: zipkin
    image: openzipkin/zipkin
    ports:
      - 9411:9411
